# Generated by Django 5.0.6 on 2024-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_short_name',
            field=models.CharField(default='UNC', max_length=25),
            preserve_default=False,
        ),
    ]
