# Generated by Django 5.0.6 on 2024-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pf', '0002_education_school_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link_to_final_work',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
