# Generated by Django 5.0.6 on 2024-06-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pf', '0003_education_link_to_final_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
