# Generated by Django 5.0.6 on 2024-06-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pf', '0004_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
